import { Metadata } from "next";
import React from "react";
import SallerAuthProdiver from "./SallerAuthProdiver";

type Props = {
   children: React.ReactNode;
};

export const metadata: Metadata = {
   title: {
      default: "SourceXBD Saller Auth",
      template: "%s | SourceXBD Saller Auth",
   },
   description: "Generated by create next app",
};

export default function AdminLayout({ children }: Props) {
   return <SallerAuthProdiver>{children}</SallerAuthProdiver>;
}
