import React, { Fragment } from "react";
import { AllProductsSvgIcon } from "@/saller/components/SvgIcons";
import dynamic from "next/dynamic";
import { Metadata } from "next";
const PageHeader = dynamic(() => import("@/saller/components/PageHeader"), {
   ssr: false,
});
const EditCompanyInformation = dynamic(
   () => import("./Components/EditCompanyInformation"),
   {
      ssr: false,
   }
);

export const metadata: Metadata = {
   title: "Edit Company Information",
   description: "Generated by create next app",
};

const icon = (
   <span className="w-6 h-6">
      <AllProductsSvgIcon />
   </span>
);

export default function ProductCreate() {
   return (
      <Fragment>
         <PageHeader icon={icon} title="Company" searchBox={false} />
         <EditCompanyInformation />
      </Fragment>
   );
}
