import { Metadata } from "next";
import React, { Fragment } from "react";
import BuyerProvider from "./BuyerProvider";

export const metadata: Metadata = {
   title: {
      default: "SourceXBD Buyer",
      template: "%s | SourceXBD Buyer",
   },
   description: "Generated by create next app",
};

type Props = {
   children: React.ReactNode;
};

export default function BuyerLayout({ children }: Props) {
   return <BuyerProvider>{children}</BuyerProvider>;
}
