import React, { Fragment } from "react";
import { CompaniesSvgIcon } from "@/saller/components/SvgIcons";
import dynamic from "next/dynamic";
import { Metadata } from "next";
const PageHeader = dynamic(() => import("@/saller/components/PageHeader"));
const SubmitVerificationDocumentsContent = dynamic(
   () => import("./Components/SubmitVerificationDocumentsContent")
);

const icon = (
   <span className="w-6 h-6">
      <CompaniesSvgIcon />
   </span>
);

export const metadata: Metadata = {
   title: "Submit Verification Documents",
   description: "Generated by create next app",
};

export default function SubmitVerificationDocuments() {
   return (
      <Fragment>
         <PageHeader icon={icon} title="Company" searchBox={false} />
         <SubmitVerificationDocumentsContent />
      </Fragment>
   );
}
