import React from "react";
import dynamic from "next/dynamic";
import { Metadata } from "next";
const OrderStatusUpdateContent = dynamic(
   () => import("./Components/OrderStatusUpdateContent")
);

export const metadata: Metadata = {
   title: "Order Status Update",
   description: "Generated by create next app",
};

export default function OrderStatusUpdate() {
   return <OrderStatusUpdateContent />;
}
