import React from "react";
import { Metadata } from "next";
import dynamic from "next/dynamic";
const OrderItemsContent = dynamic(
   () => import("./Components/OrderItemsContent")
);

export const metadata: Metadata = {
   title: "Order Items",
   description: "Generated by create next app",
};

export default function OrderItems() {
   return <OrderItemsContent />;
}
