import React from "react";
import { Metadata } from "next";
import dynamic from "next/dynamic";
const OrderCreateContent = dynamic(
   () => import("./Components/OrderCreateContent")
);

export const metadata: Metadata = {
   title: "Order Create",
   description: "Generated by create next app",
};

export default function page() {
   return <OrderCreateContent />;
}
