import React, { Fragment } from "react";
import { Metadata } from "next";
import dynamic from "next/dynamic";
const OrdersContent = dynamic(() => import("./Components/OrdersContent"));

export const metadata: Metadata = {
   title: "Orders",
   description: "Generated by create next app",
};

export default function Orders() {
   return <OrdersContent />;
}
