import { Metadata } from "next";
import React, { Fragment } from "react";
import AdminProdiver from "./AdminProdiver";

type Props = {
   children: React.ReactNode;
};

export const metadata: Metadata = {
   title: {
      default: "SourceXBD Admin",
      template: "%s | SourceXBD Admin",
   },
   description: "Generated by create next app",
};

export default function AdminLayout({ children }: Props) {
   return <AdminProdiver>{children}</AdminProdiver>;
}
