import { Metadata } from "next";
import React, { Fragment } from "react";
import SallerProdiver from "./SallerProdiver";

type Props = {
   children: React.ReactNode;
};

export const metadata: Metadata = {
   title: {
      default: "SourceXBD Saller",
      template: "%s | SourceXBD Saller",
   },
   description: "Generated by create next app",
};

export default function AdminLayout({ children }: Props) {
   return <SallerProdiver>{children}</SallerProdiver>;
}
