import React, { Fragment } from "react";
import { CompaniesSvgIcon } from "@/saller/components/SvgIcons";
import { Metadata } from "next";
import dynamic from "next/dynamic";
const PageHeader = dynamic(() => import("@/saller/components/PageHeader"), {
   ssr: false,
});
const CompanyProfileContent = dynamic(
   () => import("./Components/CompanyProfileContent"),
   {
      ssr: false,
   }
);

const icon = (
   <span className="w-6 h-6">
      <CompaniesSvgIcon />
   </span>
);

export const metadata: Metadata = {
   title: "Company Profile",
   description: "Generated by create next app",
};

export default function CompanyDetails() {
   return (
      <Fragment>
         <PageHeader icon={icon} title="Company Details" searchBox={false} />
         <CompanyProfileContent />
      </Fragment>
   );
}
