import { Metadata } from "next";
import React, { Fragment } from "react";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
   title: {
      default: "SourceXBD",
      template: "%s | SourceXBD",
   },
   description: "Generated by create next app",
};
export default function layout({ children }: { children: React.ReactNode }) {
   return (
      <Fragment>
         {children}
         <ToastContainer />
      </Fragment>
   );
}
