import { Metadata } from "next";
import React, { Fragment, ReactNode } from "react";

export const metadata: Metadata = {
   title: {
      default: "SourceXBD",
      template: "%s | SourceXBD",
   },
   description: "Generated by create next app",
};

type Props = {
   children: ReactNode;
};

export default function AuthLayout({ children }: Props) {
   return <Fragment>{children}</Fragment>;
}
