import React, { Fragment } from "react";
import { Metadata } from "next";
import dynamic from "next/dynamic";
const ProfileContent = dynamic(() => import("./Components/ProfileContent"), {
   ssr: false,
});

export const metadata: Metadata = {
   title: "Profile",
   description: "Generated by create next app",
};
export default function Profile() {
   return <ProfileContent />;
}
