import React from "react";
import { Metadata } from "next";
import dynamic from "next/dynamic";
const ReviewContent = dynamic(() => import("./Components/ReviewContent"));

export const metadata: Metadata = {
   title: "Reveiws",
   description: "Generated by create next app",
};

export default function Reviews() {
   return <ReviewContent />;
}
