import { Metadata } from "next";
import dynamic from "next/dynamic";
const DashboardContent = dynamic(
   () => import("./Components/DashboardContent"),
   {
      ssr: false,
   }
);

export const metadata: Metadata = {
   title: "Dashboard",
   description: "Generated by create next app",
};

export default function BuyerDashboard() {
   return <DashboardContent />;
}
