import React from "react";
import { Metadata } from "next";
import dynamic from "next/dynamic";
const OrderEditContent = dynamic(() => import("./Components/OrderEditContent"));

export const metadata: Metadata = {
   title: "Order Edit",
   description: "Generated by create next app",
};

type Props = {
   params: { id: string };
};

export default function page({ params }: Props) {
   return <OrderEditContent params={params} />;
}
