import React from "react";
import InventoryContent from "./Components/InventoryContent";
import { Metadata } from "next";

export const metadata: Metadata = {
   title: "Inventory",
   description: "Generated by create next app",
};

export default function Inventory() {
   return <InventoryContent />;
}
